name: Continuous Integration

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  schedule:
    - cron: "5 6 * * *"
  repository_dispatch:
    types: [liquibase-ci]
  push:
    branches:
      - main

jobs:
  build:
    name: Build & Package
    runs-on: ubuntu-latest
    needs: hibernate-test

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'temurin'
          cache: 'maven'

      - name: Install liquibase-core 0-SNAPSHOT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B clean liquibase-sdk:install-snapshot -Dliquibase.sdk.branchSearch=MATCHING_BRANCHES,master

      - name: Build and test
        run: mvn -B clean package -DskipTests=true

      - name: Save Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: liquibase-hibernate-artifacts
          path: |
            target/*.jar

      - name: Built Code Cache
        uses: actions/cache@v3.0.5
        with:
          key: built-code-${{ github.run_number }}-${{ github.run_attempt }}
          path: ./**/target

  unit-test:
    name: Test Java ${{ matrix.java }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java: [8, 11, 17, 18]

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: 'maven'

    - name: Restore Built Code Cache
      uses: actions/cache@v3.0.5
      with:
        key: built-code-${{ github.run_number }}-${{ github.run_attempt }}
        path: ./**/target

    - name: Install liquibase-core 0-SNAPSHOT
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: mvn -B clean liquibase-sdk:install-snapshot -Dliquibase.sdk.branchSearch=MATCHING_BRANCHES,master

    - name: Run Tests
      run: mvn -B surefire:test

    - name: Archive Test Results
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: test-reports-jdk-${{ matrix.java }}
        path: ./**/target/surefire-reports

  hibernate-test:
    name: Test Hibernate ${{ matrix.hibernate }}
    needs: unit-test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        hibernate: ["5.5.9.Final", "5.4.33.Final", "5.3.27.Final"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'temurin'
          cache: 'maven'

      - name: Restore Built Code Cache
        uses: actions/cache@v3.0.5
        with:
          key: built-code-${{ github.run_number }}-${{ github.run_attempt }}
          path: ./**/target

      - name: Install liquibase-core 0-SNAPSHOT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B clean liquibase-sdk:install-snapshot -Dliquibase.sdk.branchSearch=MATCHING_BRANCHES,master

      - name: Run Tests
        run: mvn -B surefire:test -Dhibernate.version=${{ matrix.hibernate }}

      - name: Archive Test Results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-reports-hibernate-{{ matrix.hibernate }}
          path: ./**/target/surefire-reports

